apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/djukicbranko/php-loki-monitoring-gitops.git
    path: charts/loki-stack
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: interview-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
