apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      initContainers:
        - name: init-loki-storage
          image: busybox
          command: ["sh", "-c", "mkdir -p /loki/wal /loki/index /loki/cache /loki/chunks"]
          volumeMounts:
            - name: loki-storage
              mountPath: /loki
      containers:
        - name: loki
          image: "{{ .Values.loki.image.repository }}:{{ .Values.loki.image.tag }}"
          ports:
            - containerPort: 3100
              name: http
          args:
            - -config.file=/etc/loki/local-config.yaml
          volumeMounts:
            - name: loki-storage
              mountPath: /loki
            - name: loki-config
              mountPath: /etc/loki  # full path inside container
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
      volumes:
        - name: loki-storage
          emptyDir: {}
        - name: loki-config
          configMap:
            name: loki-config
