apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: interview-app   # change if needed
  labels:
    app: loki
data:
  local-config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      chunk_idle_period: 5m
      chunk_retain_period: 30s
      wal:
        dir: /loki/wal        # WAL directory, writable
        recover: true

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index   # writable
        cache_location: /loki/cache           # writable
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks               # writable

    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h
