apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  labels:
    app: promtail
data:
  config.yml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_controller_name]
            regex: .*
            target_label: __tmp_controller_name
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            regex: php-app
            target_label: __tmp_php_app
          - source_labels: [__tmp_php_app]
            regex: php-app
            target_label: job
            replacement: php-app-logs
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
        pipeline_stages:
          - cri: {}

      - job_name: kubernetes-pods-app
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            action: keep
            regex: php-app
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: http
        pipeline_stages:
          - cri: {}