apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  labels:
    app: promtail
data:
  config.yml: |
    server:
      http_listen_port: 9080

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: php-container-logs
        static_configs:
        - targets:
            - localhost
          labels:
            job: php-logs
            __path__: /var/log/pods/interview-app_php-app-*/*/*.log