image:
  repository: grafana/grafana
  tag: "10.0.0"

service:
  type: ClusterIP
  port: 3000

adminUser: admin
adminPassword: admin

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
